# Generated by Django 3.2 on 2023-03-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230319_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='genre', through='reviews.GenreTitle', to='reviews.Genre'),
        ),
    ]
